name: Android Build CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build debug
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembledebug --stacktrace

  instrumentedTests:
    name: Instrumented tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Run non foss test cases
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --stacktrace --info